# Generated by Django 6.0.5 on 2026-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snake_name', models.CharField(blank=True, max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sightings/')),
                ('length_cm', models.PositiveIntegerField(default=50)),
                ('thickness', models.CharField(blank=True, choices=[('thin', 'Thin'), ('medium', 'Medium'), ('thick', 'Thick')], max_length=20)),
                ('pattern', models.JSONField(blank=True, default=list)),
                ('head_shape', models.CharField(blank=True, choices=[('rounded', 'Rounded'), ('triangular', 'Triangular'), ('narrow', 'Narrow')], max_length=20)),
                ('eye_type', models.CharField(blank=True, choices=[('round', 'Round pupil'), ('vertical', 'Vertical pupil'), ('not_visible', 'Not visible')], max_length=20)),
                ('behaviour', models.JSONField(blank=True, default=list)),
                ('condition', models.JSONField(blank=True, default=list)),
                ('num_snakes', models.PositiveSmallIntegerField(default=1)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('location_type', models.CharField(blank=True, choices=[('garden', 'Garden'), ('forest', 'Forest'), ('roadside', 'Roadside'), ('farmland', 'Farmland'), ('wetland', 'Wetland'), ('urban', 'Urban')], max_length=20)),
                ('micro_habitat', models.JSONField(blank=True, default=list)),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('weather', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('add_to_database', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
