# Generated by Django 6.0.5 on 2026-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakesighting',
            name='inat_common_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='snakesighting',
            name='inat_scientific_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='snakesighting',
            name='inat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakesighting',
            name='inat_taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
